USE SYS;
SET FOREIGN_KEY_CHECKS = 0;
drop table if exists TIPO_USUARIO;
drop table if exists USUARIO;
drop table if exists HOTEL;
drop table if exists HABITACION;
drop table if exists METODO_PAGO;
drop table if exists RESERVA;
drop table if exists DETALLE_PAGO;

SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE TIPO_USUARIO CASCADE;
DROP TABLE USUARIO CASCADE;
DROP TABLE HOTEL CASCADE;
DROP TABLE HABITACION CASCADE;
DROP TABLE METODO_PAGO CASCADE;
DROP TABLE DETALLE_PAGO CASCADE;
DROP TABLE RESERVA CASCADE;

CREATE TABLE TIPO_USUARIO (
	tipo_usuario_id INT PRIMARY KEY,
    nombre_tipo_usuario VARCHAR(45) NOT NULL

);

CREATE TABLE USUARIO (
	usuario_id INT AUTO_INCREMENT PRIMARY KEY,
    rut_usuario VARCHAR(12) NOT NULL,
    nombre_usuario VARCHAR(45) NOT NULL,
    apellido_usuario VARCHAR(45) NOT NULL,
    correo_usuario VARCHAR(45) NOT NULL,
    contrasena VARCHAR(200) NOT NULL,
    telefono_usuario VARCHAR(10) NOT NULL,
    tipo_usuario_id INT NOT NULL
    
);

ALTER TABLE USUARIO
ADD CONSTRAINT USUARIO_TIPO_USUARIO_FK FOREIGN KEY (tipo_usuario_id)
REFERENCES TIPO_USUARIO (tipo_usuario_id);

CREATE TABLE HOTEL (
	hotel_id INT PRIMARY KEY,
    nombre_hotel VARCHAR(45) NOT NULL,
    direccion VARCHAR(45) NOT NULL,
    categoria VARCHAR(45)
    
);

CREATE TABLE HABITACION (
	habitacion_id INT PRIMARY KEY,
    hotel_id INT NOT NULL,
    tipo VARCHAR(45) NOT NULL,
    capacidad INT NOT NULL,
    precio_noche INT NOT NULL,
    cant_disponibles INT NOT NULL

);

ALTER TABLE HABITACION
ADD CONSTRAINT HABITACION_HOTEL_FK FOREIGN KEY (hotel_id)
REFERENCES HOTEL (hotel_id);

CREATE TABLE METODO_PAGO (
	metodo_pago_id INT AUTO_INCREMENT PRIMARY KEY,
    tipo_metodo VARCHAR(45) NOT NULL

);

CREATE TABLE DETALLE_PAGO (
	detalle_pago_id INT AUTO_INCREMENT PRIMARY KEY,
    metodo_pago_id INT NOT NULL,
    pago_inicial INT NOT NULL,
    pago_pendiente INT NOT NULL,
    fecha_pago DATE NOT NULL

);
ALTER TABLE DETALLE_PAGO
ADD CONSTRAINT DETALLE_PAGO_METODO_PAGO_FK FOREIGN KEY (metodo_pago_id)
REFERENCES METODO_PAGO (metodo_pago_id);

CREATE TABLE RESERVA (
	reserva_id INT AUTO_INCREMENT PRIMARY KEY,
    habitacion_id INT NOT NULL,
    usuario_id INT NOT NULL,
    detalle_pago_id INT NOT NULL,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    cant_personas INT NOT NULL

);

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_HABITACION_FK FOREIGN KEY (habitacion_id)
REFERENCES HABITACION (habitacion_id);

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_USUARIO_FK FOREIGN KEY (usuario_id)
REFERENCES USUARIO (usuario_id);

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_DETALLE_PAGO_FK FOREIGN KEY (detalle_pago_id)
REFERENCES DETALLE_PAGO (detalle_pago_id);


/*. INSERCIÓN DE DATOS. */ 

/* TABLA TIPO USUARIO */
INSERT INTO TIPO_USUARIO VALUES(1,'ADMINISTRADOR');
INSERT INTO TIPO_USUARIO VALUES(2,'CLIENTE');
INSERT INTO TIPO_USUARIO VALUES(3,'TRABAJADOR');

/* TABLA USUARIO */
INSERT INTO USUARIO VALUES('12345678','Juan','Perez','juan.perez@gmail.com','912345678',2);
INSERT INTO USUARIO VALUES('16485938','Rodolfo','Celis','rodolfo.celis@gmail.com','985947364',3);
INSERT INTO USUARIO VALUES('19375618','Miguel','Jara','miguel.jara@gmail.com','909384937',1);


/* TABLA HOTEL */
INSERT INTO HOTEL VALUES(1,'HOTEL PACIFIC REEF','Avenida El Salvador 123',NULL);

/* TABLA HABITACION */

INSERT INTO HABITACION VALUES(1,1,'STANDARD TWIN', 2, 80000,10);
INSERT INTO HABITACION VALUES(2,1,'STANDARD MATRIMONIAL', 2, 100000,10);

/* TABLA METODO_PAGO */

INSERT INTO METODO_PAGO VALUES(1,'CREDITO');
INSERT INTO METODO_PAGO VALUES(2,'DEBITO');
INSERT INTO METODO_PAGO VALUES(3,'TRANSFERENCIA');

/* TABLA DETALLE_PAGO */

INSERT INTO DETALLE_PAGO VALUES(1,1,30000,70000,STR_TO_DATE('20-09-2023','%d-%m-%Y'));
INSERT INTO DETALLE_PAGO VALUES(2,2,50000,175000,STR_TO_DATE('19-09-2023','%d-%m-%Y'));
INSERT INTO DETALLE_PAGO VALUES(3,3,50000,175000,STR_TO_DATE('18-09-2023','%d-%m-%Y'));

/* TABLA RESERVA */

INSERT INTO RESERVA VALUES(1,1,1,2,STR_TO_DATE('20-09-2023','%d-%m-%Y'),STR_TO_DATE('22-09-2023','%d-%m-%Y'),2);

SELECT * FROM TIPO_USUARIO;
SELECT * FROM USUARIO;
SELECT * FROM HOTEL;
SELECT * FROM HABITACION;
SELECT * FROM METODO_PAGO;
SELECT * FROM DETALLE_PAGO;
SELECT * FROM RESERVA;